export default [
  // 'debug',
  // 'normalize.css',
  // 'validator',
  // 'isomorphic-fetch',
  'react',
  // 'react-addons-css-transition-group',
  'react-dom',
  // 'react-router-redux',
  // 'react-router',
  // 'history',
  // 'react-toolbox',
  // 'react-helmet',
  // 'redux-act',
  // 'redux-form',
  // 'redux-promise',
  // 'redux-logger',
  // 'classnames',
  // 'react-css-modules',
  // 'serialize-javascript',
  // 'svg-inline-react',
  // 'fastclick',
  // 'fontfaceobserver',
  // 'socket.io-client',
  // 'react-select',
  // 'react-time',
  // 'redux-search',
  // 'redux-analytics',
  // 'redux-recycle',
  // 'howler',
  // 'moment',
  // 'parse-link-header',
  // 'react-motion',
  // 'react-intl',
  // 'normalizr',
  // 'reselect',
  // 'react-joyride',
  // 'react-transitive-number',
  // 'react-typist',
  // 'react-pure-render',
  // 'react-themeable',
  // 'react-visibility-sensor',
];
